# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pages-build-deployment

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
      with:
        repository: DannyGooo/yonghuiliu-dev
        ref: main
        token: ${{ secrets.SSH_KEY }}

        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    
    - name: Configure files
      run: |
        sed -i 's#"homepage": "/"#"homepage": "https://yonghuiliu.github.io/"#' package.json
        sed -i 's/BrowserRouter/HashRouter/g' src/index.js
    - run: npm run build --if-present
    
    - name: List current directory
      run: ls -la

    - name: List build directory
      run: ls -la build/

    
    - name: Upload GitHub Pages artifact
      # uses: actions/upload-pages-artifact@v1.0.3
      uses: actions/upload-pages-artifact@v1
      with:
        path: build/
        name: github-pages

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: github-pages
        
  # deploy:
    
  #   runs-on: ubuntu-latest
    
  #   needs: build
    
  #   permissions:
  #     pages: write
  #     id-token: write
      
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v1.0.9
